name: Publish Image in AWS ECR

on:
  push:
    branches: [main]
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      AWS_REGION:
        required: true
      AWS_ACCOUNT_ID:
        required: true
      ECR_REPOSITORY:
        required: true
      CONTAINER_NAME:
        required: true
      ECS_SERVICE:
        required: true
      ECS_CLUSTER:
        required: true
      ECS_TASK_DEFINITION:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      SLACK_WEBHOOK_URL:
        required: false
      GOOGLE_CHAT_WEBHOOK_URL:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
      ECS_SERVICE: ${{ secrets.ECS_SERVICE }}
      ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}
      ECS_TASK_DEFINITION: ${{ secrets.ECS_TASK_DEFINITION }}

    steps:
      - name: Checkout current repo (full history)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0


      - name: Install wkhtmltopdf
        run: |
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf
          curl -sLO https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Extract branch name
        id: extract_branch
        run: |
          branch="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          branch="${branch//\//-}"
          branch=$(echo "$branch" | tr '[:upper:]' '[:lower:]')
          echo "branch=$branch" >> $GITHUB_OUTPUT

      - name: Get Git Hashes
        id: git_hashes
        run: |
          echo "short_hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "long_hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Run Trivy vulnerability scanner (filesystem)
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'template'
          template: 'html.tpl'
          output: 'trivy-fs-report.html'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

      - name: Convert FS Report to PDF
        if: always()
        run: |
          if [ -f trivy-fs-report.html ]; then
            wkhtmltopdf trivy-fs-report.html trivy-fs-report.pdf
          fi

      - name: Build Docker Image
        id: build-image
        run: |
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/${ECR_REPOSITORY}"
          TAG="${{ steps.extract_branch.outputs.branch }}-${GITHUB_RUN_NUMBER}"
          
          docker build \
            --build-arg="PUPPETEER_SKIP_DOWNLOAD_ARG=true" \
            --build-arg="APIM_VERSION=4.3.2" \
            -t $IMAGE_URI:$TAG .
          
          echo "image_uri=$IMAGE_URI" >> $GITHUB_OUTPUT
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          image-ref: '${{ steps.build-image.outputs.image_uri }}:${{ steps.build-image.outputs.tag }}'
          format: 'template'
          template: 'html.tpl'
          output: 'trivy-image-report.html'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Convert Image Report to PDF
        if: always()
        run: |
          if [ -f trivy-image-report.html ]; then
            wkhtmltopdf trivy-image-report.html trivy-image-report.pdf
          fi

      - name: Push Docker Image
        run: |
          IMAGE_URI="${{ steps.build-image.outputs.image_uri }}"
          TAG="${{ steps.build-image.outputs.tag }}"
          docker push $IMAGE_URI:$TAG

      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition ${{ secrets.ECS_TASK_DEFINITION }} --query taskDefinition > task-definition.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ secrets.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image_uri }}:${{ steps.build-image.outputs.tag }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ secrets.ECS_SERVICE }}
          cluster: ${{ secrets.ECS_CLUSTER }}
          wait-for-service-stability: true

      - name: Upload Trivy Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-reports
          path: '*.pdf'

  notify:
    needs: [build]
    if: always()
    uses: ./.github/workflows/notifications.yml
    with:
      job_status: ${{ needs.build.result }}
    secrets: inherit