name: Upload Image Name

on: workflow_call

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: image-name

      - name: Checkout other repository
        uses: actions/checkout@v4
        with:
          repository: Fundacion-Dinero-Conciencia/infra-live
          token: ${{ secrets.OTHER_REPO_TOKEN }}
          path: other-repo

      - name: Update image name in task.auto.tfvars
        run: |
          IMAGE_NAME=$(cat image_name.txt)
          sed -i 's|image = ".*"|image = "'"$IMAGE_NAME"'"|' other-repo/aws-org-belat/environments/cuenta-pro/task.auto.tfvars

      - name: Commit and push
        run: |
          cd other-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add aws-org-belat/environments/cuenta-pro/task.auto.tfvars
          git commit -m "Update image name in task.auto.tfvars from build workflow"
          git push