name: Upload Image Name on Repo Terraform

on:
  workflow_call:
    secrets:
      OTHER_REPO_TOKEN:
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: image-name

      - name: Checkout other repository
        uses: actions/checkout@v4
        with:
          repository: Fundacion-Dinero-Conciencia/infra-live
          token: ${{ secrets.OTHER_REPO_TOKEN }}
          path: other-repo

      - name: Update image name in task.auto.tfvars
        run: |
          IMAGE_NAME=$(cat image_name.txt)
          sed -i 's|image = ".*"|image = "'"$IMAGE_NAME"'"|' other-repo/aws-org-belat/environments/cuenta-pro/task.auto.tfvars

      - name: Commit and push
        run: |
          cd other-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add aws-org-belat/environments/cuenta-pro/task.auto.tfvars
          
          # Verificamos si hay cambios en el staging area antes de hacer el commit
          if git diff --cached --quiet; then
            echo "No hay cambios detectados en task.auto.tfvars. Saltando commit."
          else
            git commit -m "Update image to $(cat ../image_name.txt)"
            git push
          fi